Demo/Controllers/GoodsController.cs
using Bll;
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo.Controllers
{
    public class GoodsController : Controller
    {
        private MMEntities db = new MMEntities();

        // GET: Goods
        public ActionResult Index(string SearchGname, int pageSize = 5, int curIndex = 1, int tid=0)
        {
            int count=0;
         
            //方法count引用变量
            var lists = GoodsBll.GetList(new goods(), SearchGname, pageSize, curIndex, out count,tid);
            //总页数
            double pagecount = Math.Ceiling(count * 1.0 / pageSize);
            ViewBag.pagecount = pagecount;
            ViewBag.curIndex = curIndex;
            ViewBag.tid = new SelectList(db.type, "tid", "tname");
            ViewBag.action = "/goods/Index";
            ViewBag.SearchGname = SearchGname;
            return View(lists);
        }
       
        public ActionResult Edit(int gid = 0)
        {
            goods model = new goods();
            if (gid > 0)
            {
                model = GoodsBll.Getgoods(gid);
            }
            //绑定下拉框
            goods goods = db.goods.Find(gid);
            ViewBag.tid = new SelectList(db.type, "tid", "tname");
            return View(model);
        }
      
        [HttpPost]

        public ActionResult DoEdit(goods m,int gid = 0)
        {
            if (Request.Files.Count > 0)
            {
                HttpPostedFileBase f = Request.Files["uploadFileName"];
                string extName = System.IO.Path.GetExtension(f.FileName);
                if (extName != ".jpeg" && extName != ".gif" && extName != ".jpg" && extName != ".png" && extName != ".JPG" && extName != ".PNG" && extName != ".JPEG" && extName != ".GIF")
                {
                    //返回前一页
                    return Content("<script>alert('文件格式不合适，请重新上传');history.go(-1);</script>");
                }
              
                f.SaveAs(Server.MapPath("~/img/upload/" + f.FileName));
                m.img =f.FileName;
            }
            if (m.gid > 0)
            {
                GoodsBll.Update(m);
            }
            else
            {
                GoodsBll.Insert(m);
            }
         
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int gid = 0)
        {

            if (gid > 0)
            {
                GoodsBll.Delete(gid);
            }
            return RedirectToAction("Index");
        }
    }
}

Demo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Demo/Controllers/PlansController.cs
using Bll;
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo.Controllers
{
    public class PlansController : Controller
    {
        // GET: Plans
        public ActionResult Index(string SearchPname,int pageSize=5, int curIndex=1)
        {
            int count = 0;
            //方法count引用变量
            var lists = PlansBll.GetList(new plans(), SearchPname,pageSize,curIndex,out count);
            //总页数
            double pagecount = Math.Ceiling(count * 1.0 / pageSize);
            ViewBag.pagecount = pagecount;
            ViewBag.curIndex = curIndex;
            ViewBag.action="/Plans/Index";
            ViewBag.SearchPname = SearchPname;
            return View(lists);
        }
     
        public ActionResult Edit(int pid = 0)
        {
            plans model = new plans();
            model.ptime = DateTime.Now;
            if (pid > 0)
            {
                model = PlansBll.Getplans(pid);
            }
          
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(plans m)
        {

            if (m.pid > 0)
            {
                PlansBll.Update(m);
            }
            else
            {
                PlansBll.Insert(m);
            }
            return RedirectToAction("Index");
        }
        public ActionResult Delete(int pid = 0)
        {

            if (pid > 0)
            {
                PlansBll.Delete(pid);
            }
            return RedirectToAction("Index");
        }
    }
}

Demo/Controllers/UsersController.cs
using Bll;
using Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace Demo.Controllers
{
    public class UsersController : Controller
    {
        // GET: Users
        public ActionResult Index(string SearchUname, int pageSize = 5, int curIndex = 1)
        {
            int count = 0;
            //方法count引用变量
            var lists = UsersBll.GetList(new users(), SearchUname, pageSize, curIndex, out count);
            //总页数
            double pagecount = Math.Ceiling(count * 1.0 / pageSize);
            ViewBag.pagecount = pagecount;
            ViewBag.curIndex = curIndex;
            ViewBag.action = "/Users/Index";
            ViewBag.SearchUname = SearchUname;
            return View(lists);
        }
      

        public ActionResult Edit(int uid = 0)
        {
            users model = new users();
            model.birth = DateTime.Now;
            if (uid > 0)
            {
                model = UsersBll.Getusers(uid);
            }
            return View(model);
        }
        public ActionResult Reg(int uid = 0)
        {
            users model = new users();
            model.birth = DateTime.Now;
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(users m)
        {
           
            if (m.uid > 0)
            {
                UsersBll.Update(m);
            }
            else
            {
                UsersBll.Insert(m);
            }
            return RedirectToAction("Index");
        }
        
        public ActionResult Delete(int uid = 0)
        {
          
            if (uid > 0)
            {
                UsersBll.Delete(uid);
            }
            return RedirectToAction("Index");
        }
        //登录
        public ActionResult login()
        {
            return View();
        }
        public ActionResult DoLogin(users m)
        {
            var model = UsersBll.Login(m);
            if (model != null && model.uid > 0)
            {
                //保持登录状态
                //true 有效期是永久（根据配置文件的时间，单位是分钟）
                FormsAuthentication.SetAuthCookie(model.uname, true);
                //false 有效期是会话的
                //FormsAuthentication.SetAuthCookie(model.uname, false);
                //跨控制器
                //return Redirect("/Home/Index");
                return Content("<script>alert('登陆成功');window.open('" + Url.Content("/Home/Index") + "', '_self')</script>", "text/html");

            }
            else
            {

                return Content("<script>alert('用户名或密码有误！');history.go(-1);</script>");
            }

        }
        //退出
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("login");
        }
        //注册
     
        public ActionResult DoReg(users m)
        {
          
                UsersBll.Insert(m);
            return Content("<script>alert('注册成功');window.open('" + Url.Content("/Users/login") + "', '_self')</script>", "text/html");
        
        }
    }
}

Demo/Views/Goods/Edit.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
@model Model.goods
 
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>出入库</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <style>
        body {
            background-color: cadetblue;
            margin-top: 20px;
        }

        #a {
            margin-left: 40px;
            color: darkblue;
            font-size: 20px;
        }
    </style>
</head>
<body>
    @*@using (Html.BeginForm("Edit", "Goods", FormMethod.Post))
    {*@
    <form action="/Goods/DoEdit" method="post" enctype="multipart/form-data">
        <div class="container">
            <h3 class="text-center" style="margin-left:80px">物资出入库</h3>
            @Html.Hidden("gid")
            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>物资名</h4></div>
                    <div class="col-md-8">
                        @Html.TextBox("gname", null, new { @class = "form-control", @placeholder = "请输入物资名" })
                        @Html.ValidationMessageFor(m => m.gname, "", new { @class = "text-danger" })

                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>图片</h4></div>
                    <div class="col-md-8">
                        <input type="file" name="uploadFileName" value="请选择图片"/>
                    </div>
                </div>
            </div>

            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>来源</h4></div>
                    <div class="col-md-8">
                        @Html.TextBox("source", null, new { @class = "form-control", @placeholder = "请输入来源" })
                    </div>
                </div>
            </div>

            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>数量</h4></div>
                    <div class="col-md-8">
                        @Html.TextBox("num", null, new { @class = "form-control", @placeholder = "请输入数量" })
                        @Html.ValidationMessageFor(m => m.num, "", new { @class = "text-danger" })

                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>单位</h4></div>
                    <div class="col-md-8">
                        @Html.TextBox("unit", null, new { @class = "form-control", @placeholder = "请输入单位" })
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>备注</h4></div>
                    <div class="col-md-8">
                        @Html.TextArea("gremark", null, new { @class = "form-control", @placeholder = "请输入备注" })
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>类型</h4></div>
                    <div class="col-md-8">
                        @Html.DropDownList("tid", null,new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.tid, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="row form-group">
                <div class="col-md-6 col-md-push-6">
                    <button type="submit" class="btn btn-default btn-lg">
                        保存
                    </button>
                </div>
            </div>
        </div>
        <div id="a">
            @Html.ActionLink("返回主页", "Index", "Goods")
        </div>
    </form>
    @*}*@
</body>
</html>

Demo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Demo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@*轮播*@
    <div id="myCarousel" class="carousel slide" data-interval="2000">
        <!-- 轮播（Carousel）指标 -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
        </ol>
        <!-- 轮播（Carousel）项目 -->
        <div class="carousel-inner">
            <div class="item active">
                <img src="~/img/lunbo1.jpg" style="width: 100%; height: 500px" alt="First slide">
            </div>
            <div class="item">
                <img src="~/img/lunbo2.jpg" style="width: 100%; height: 500px" alt="Second slide">
            </div>
            <div class="item">
                <img src="~/img/lunbo3.jpg" style="width: 100%; height: 500px" alt="Third slide">
            </div>
            <div class="item">
                <img src="~/img/lunbo4.jpg"style="width: 100%; height: 500px" alt="Fourth slide">
            </div>
        </div>
        <!-- 轮播（Carousel）导航 -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    @*关于我们*@
    <div class="row" style="color:white">
        <div class="col-md-4">
            <img src="~/img/kouzhao.jpg" style="width: 200px; height: 200px; margin-top: 40px" class="img-circle" />
        </div>
        <div class="col-md-8" style="margin-top:30px">
            <h3 style="text-align:center">关于我们</h3>
            <p>防疫物资管理系统从防疫物资的采购、入库以及机构内对防疫物资使用消耗情况的管理、机构间调拨、科室间调拨等方面对防疫物资进行全流程管理，视疫情最新态势,及时高效的完成防疫物资统-调拨，第-时间用于疫情防控工作现场。在疫情常态化防控的大环境下,为各级各类疫情防控的管理机构、业务机构提供规范化管理流程及强有力的数据支撑。</p>
        </div>
    </div>
    @*我们的服务*@
    <div class="row">
        <div class="jumbotron" style="background-color:steelblue;margin-top:40px">
            <div class="row ">
                <h3>我们的服务</h3>
                <p>解决疫情期间各级防控指挥部、卫健委、医疗机构等防疫重点单位在应急物资管理工作上的难点,畅通需求与保障渠道,全力保证疫情期间防疫物资有效供给,确保紧缺防疫物资能高效的用于疫情防控工作,加强对疫情防控应急物资的管理。</p>
            </div>
            <div class="row  pull-left">
                <div class="col-md-3">
                    <div class="panel text-center">
                        <div class="panel-heading">
                            <span class="glyphicon glyphicon-briefcase"></span>
                            <h5>@Html.ActionLink("物资管理", "Index", "Goods")</h5>
                        </div>
                        <div class="panel-body ">
                            <p>对物资进行系统化，规范化收集及发放</p>

                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="panel text-center">
                        <div class="panel-heading">
                            <span class="glyphicon glyphicon-list"></span>
                            <h5>@Html.ActionLink("制定计划", "Index", "Plans")</h5>
                        </div>
                        <div class="panel-body">
                            <p>规划时间，创建计划，完成计划打卡</p>

                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="panel text-center">
                        <div class="panel-heading">
                            <span class="glyphicon glyphicon-user"></span>
                            <h5>@Html.ActionLink("用户管理", "Index", "Users")</h5>
                        </div>
                        <div class="panel-body">
                            <p>为用户提供创建，修改，注销用户等功能</p>

                        </div>
                    </div>
                </div>
                <div class="col-md-3">
                    <div class="panel text-center">
                        <div class="panel-heading">
                            <span class="glyphicon glyphicon-pencil"></span>
                            <h5>@Html.ActionLink("联系我们", "Contact", "Home")</h5>
                        </div>
                        <div class="panel-body">
                            <p>
                                如果有任何问题，欢迎联系我们
                            </p>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    

Demo/Views/Plans/Edit.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
@model Model.plans
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>计划编辑</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <style>
        body {
            background-color: cadetblue;
            margin-top: 20px;
        }

        #a {
            margin: 270px 0 0 40px;
            color: darkblue;
            font-size: 20px;
        }
    </style>
</head>
<body>  
    <form action="/Plans/Edit" method="post">
        <div class="container">
            <h3 class="text-center" style="margin-left:80px">计划编辑</h3>
            @Html.Hidden("pid")
            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>计划标题</h4></div>
                    <div class="col-md-8">
                        @Html.TextBox("pname", null, new { @class = "form-control", @placeholder = "请输入计划标题" })
                        @Html.ValidationMessageFor(m => m.pname, "", new { @class = "text-danger" })
                    </div>

                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>计划时间</h4></div>
                    <div class="col-md-8">
                        <input type="date" name="ptime" value="@Model.ptime.ToString("yyyy-MM-dd")" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>计划内容</h4></div>
                    <div class="col-md-8">
                        @Html.TextArea("pmark", null, new { @class = "form-control", @placeholder = "请输入计划内容" })
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6 col-md-push-6">
                    <button type="submit" class="btn btn-default btn-lg">
                        保存
                    </button>
                </div>
            </div>
        </div>
        <div id="a">
            @Html.ActionLink("返回主页", "Index", "Plans")
        </div>
       </form>
</body>
</html>

Demo/Views/Shared/Main.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>首页</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <style>
        body {
            background-color: cadetblue;
        }

        .a p, i, h3 {
            color: white;
        }

       
        .panel:hover {
            box-shadow: 5px 0px 40px rgb(0 0 0);
        }
        .panel-heading{
            background-color:aquamarine;
        }
      
    </style>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <!--顶部-->
                <div class="row">
                    <div class="col-md-1"><img src="~/img/logo.png" /> </div>
                    <div class="col-md-4"><div style="margin:70px 0 0 25px;position:absolute"><h3>@Html.ActionLink("防疫物资管理系统", "Index", "Home", new { @style = "color:white;text-decoration:none;" })</h3></div></div>
                    <div class="col-md-3 col-md-offset-3 text-right" style="margin-top:30px;">

                        <img src="~/img/china.png">
                        <span>中文版</span>
                        |
                        <img src="~/img/uk.png">
                        <span>英语版</span>
                        <br />
                        <br>

                        <a href="/Users/Logout" class="btn btn-danger"><span class="glyphicon glyphicon-log-out"></span>退出登录</a>
                    </div>
                </div>
                <!--导航栏-->
                <div class="row">
                    <nav class="navbar-inverse">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                                @Html.ActionLink("主页", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                            </div>
                            <div class="navbar-collapse collapse">
                                <ul class="nav navbar-nav">
                                    <li>@Html.ActionLink("物资管理", "Index", "Goods")</li>
                                    <li>@Html.ActionLink("计划管理", "Index", "Plans")</li>
                                    <li>@Html.ActionLink("用户管理", "Index", "Users")</li>
                                    <li>@Html.ActionLink("联系我们", "Contact", "Home")</li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
                @*导航内容*@

                <div class="row">
                    <div class="col-md-12">
                        @RenderBody()
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12" style="margin-top:30px">
                        <hr />
                        <p class="text-center">Copyright © 2022 Adobe Systems Incorporated. All rights reserved. </p>
                    </div>
                  
                </div>
            </div>
            </div>
        </div>
  

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Demo/Views/Users/Edit.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
@model Model.users
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>用户编辑</title>
    <link rel="stylesheet" href="~/Content/bootstrap.css" />
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <style>
        body {
            background-color: cadetblue;
            margin-top: 20px;
        }

        #a {
            margin-left: 40px;
            color: darkblue;
            font-size: 20px;
        }
    </style>
</head>
<body>
    <form action="/Users/Edit" method="post">
        <div class="container">
            <h3 class="text-center" style="margin-left:80px">用户编辑</h3>
            @Html.Hidden("uid")
            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>用户名</h4></div>
                    <div class="col-md-8">
                        @Html.TextBox("uname", null, new { @class = "form-control", @placeholder = "请输入用户名" })
                        @Html.ValidationMessageFor(m => m.uname, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>密码</h4></div>
                    <div class="col-md-8">
                        @Html.TextBox("pwd", null, new { @class = "form-control", @placeholder = "请输入密码" })
                        @Html.ValidationMessageFor(m => m.pwd, "", new { @class = "text-danger" })

                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>性别</h4></div>
                    <div class="col-md-8">
                        @Html.RadioButton("sex", "男",new { @checked = "true" }) 男 @Html.RadioButton("sex", "女") 女
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>年龄</h4></div>
                    <div class="col-md-8">
                        @Html.TextBox("age", null, new { @class = "form-control", @placeholder = "请输入年龄" })
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>生日</h4></div>
                    <div class="col-md-8">
                        <input type="date" name="birth" value="@Model.birth.ToString("yyyy-MM-dd")" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>邮箱</h4></div>
                    <div class="col-md-8">
                        @Html.TextBox("email", null, new { @class = "form-control", @placeholder = "请输入邮箱" })
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6 col-md-push-3">
                    <div class="col-md-3 col-md-push-1" style=""><h4>电话</h4></div>
                    <div class="col-md-8">
                        @Html.TextBox("tel", null, new { @class = "form-control", @placeholder = "请输入电话" })
                    </div>
                </div>
            </div>
            <div class="row form-group">
                <div class="col-md-6 col-md-push-6">
                    <button type="submit" class="btn btn-default btn-lg">
                        保存
                    </button>
                </div>
            </div>
        </div>
        <div id="a">
            @Html.ActionLink("返回主页", "Index", "Users")
        </div>
    </form>
</body>
</html>

Demo/Views/Users/login.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>登录</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
  <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    <style>

        #main {
            margin: 0 auto;
            width: 100%;
            height: 770px;
            border: 1px solid black;
            background-image: url('/img/登录背景.jpg');
            background-position: center;
            background-size: 100% 770px;
            background-repeat: no-repeat;
            /* -webkit-filter: blur(10px);
            -moz-filter: blur(10px);
            filter: blur(10px);*/
        }
            
        #login {
            width: 30%;
            height: 250px;
            margin: 240px 0 0 140px;
        }

        .imgNamePwd {
            width: 40px;
            height: 40px;
        }

      

        #txtName {
            width: 250px;
            height: 30px;
            position: absolute;
            margin: 50px 0 0 10px;
            border-radius: 16px 16px 16px 16px;
        }

        #txtPwd {
            width: 250px;
            height: 30px;
            position: absolute;
            margin: 50px 0 0 10px;
            border-radius: 16px 16px 16px 16px;
        }

        .imgNamePwd {
            margin-top: 46px;
        }

        #imgLogin {
            position: absolute;
            margin-top: 20px;
        }


        a {
            float: left;
            margin-top: 180px;
            color: darkblue;
            font-size: 20px;
        }

        #isShow {
            margin-left: 236px;
            margin-top: 57px;
            position: absolute;
        }
    </style>
</head>
<body>
    <div class="row"></div>
    <div id="main" class="col-md-12">
        <div class="row">
            <div id="login" class="col-md-5 pull-left"  style="border-radius: 25px; background: linear-gradient(rgb(0 0 0 / 0),rgb(0 0 0 / 0.35)); height: 300px">
                <div class="row text-center"> <h3>请登录</h3></div>
                <form action="/Users/DoLogin" method="post">
                    <div class="row">
                        <div class="col-md-2"><img src="/img/用户名.png" class="imgNamePwd img-responsive" /></div><div class="col-md-10"><input type="text" class="form-control" id="txtName" name="uname" placeholder="请输入用户名" /></div>
                    </div>
                    <div class="row">
                        <div class="col-md-2"><img src="/img/密码.png" class="imgNamePwd img-responsive" /></div><div class="col-md-10"><input type="password" id="txtPwd" name="pwd" class="form-control" placeholder="请输入密码" /><img src="/img/不显示.png" id="isShow" width="20" height="20" /></div>
                    </div>
                    <div class="row">
                        <div class="col-md-3  col-md-offset-4">
                            <button type="submit" class="form-control btn btn-default" id="imgLogin">登录</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <a>@Html.ActionLink("如果没有账号，请点击此处注册!", "Reg", "Users")</a>  
    </div>
    <script type="text/javascript">
            //是否隐藏密码
            var isshow = document.getElementById('isShow');
            var pwd = document.getElementById('txtPwd');
            var flag = 0;
            isshow.onclick = function () {
                //点击一次后，flag一定进行改变
                if (flag == 0) {
                    pwd.type = 'text';
                    isshow.src = '/img/显示.png';
                    flag = 1;
                }
                else {
                    pwd.type = 'password';
                    isshow.src = '/img/不显示.png';
                    flag = 0;
                }
        }
       
    </script>
</body>

</html>